apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trial
  labels:
    app: trial
    release: prometheus
  name: trial
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: trial
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: trial